from shared.config import settings

AUDIO_TOPIC = settings.KAFKA_AUDIO_TOPIC
TRANSCRIPT_TOPIC = settings.KAFKA_TRANSCRIPT_TOPIC
GLOSS_TOPIC = settings.KAFKA_GLOSS_TOPIC
ANIMATION_TOPIC = settings.KAFKA_ANIMATION_TOPIC
METRICS_TOPIC = settings.KAFKA_METRICS_TOPIC
DLQ_TOPIC = settings.KAFKA_DLQ_TOPIC